#!/usr/bin/env bash

TITLE=$(hyprctl activewindow -j | jq -r .title)
RETURN=""


if [[ $TITLE == "null" ]]
then
    RETURN="Empty"
else
    if [[ ${#TITLE} -ge 50 ]]
    then
	RETURN=${TITLE:0:49}...
    else
	RETURN=$TITLE
    fi
fi

echo " "$RETURN
