#!/usr/bin/env bash

BATTDIR=/sys/class/power_supply/BAT0
PERCENT=$(/bin/cat $BATTDIR/capacity)
STATUS=$(/bin/cat $BATTDIR/status)

declare -A ICONS

ICONS[Discharging]="󰂎, 󰁺, 󰁻, 󰁼, 󰁽, 󰁾, 󰁿, 󰂀, 󰂁, 󰂂, 󰁹, 󰂄"
ICONS[Charging]="󰢟 ,󰢜 ,󰂆 ,󰂇 ,󰂇 ,󰢝 ,󰂉 ,󰢞 ,󰂊 ,󰂋 ,󰂅 , 󰂄"

! [[ $STATUS =~ Dischargin ]] && STATUS=Charging

IFS=', ' read -r -a ICONS_ARRAY < <(echo ${ICONS[$STATUS]})

case $1 in
    icon)
	echo ${ICONS_ARRAY[$(($PERCENT/10))]}
	;;
    capacity)
	echo $PERCENT%
	;;
    status)
	echo $STATUS
	;;
    *|?)
    echo "Error"
    exit 1
    ;;
esac
exit 0
