#!/usr/bin/env bash

INTERFACE=$(basename /sys/class/net/w*)
STATE=$(ip link show $INTERFACE | grep -oP 'state\s+\K\w+')
read -r SSID SIGNAL < <(iw dev $INTERFACE link | awk '/SSID:|signal:/ { print $2 }' | tr '\n' ' ')

icon () {
    declare -A ICONS; ICONS+=([down]="󰤮", [up]="󰤨, 󰤥, 󰤢, 󰤟, 󰤯")
    RANGES=("0|[1-4][0-9]|50" "5[1-9]|60" "6[1-9]|70" "7[1-9]|80" "8[1-9]|9[0-9]|1[0-9]+")

    case ${STATE,,} in
	down)
	    echo ${ICONS[down]}
	    ;;
	up)	    
	    for i in {0..4}
	    do
		[[ $(($SIGNAL * -1)) =~ ${RANGES[$i]} ]] && INDEX=$i; break
	    done
	    IFS=', ' read -r -a ARRAY_UP < <(echo ${ICONS[up]})
	    echo ${ARRAY_UP[$INDEX]}
	    ;;
    esac
}

declare -A OUTPUT
OUTPUT+=([interface]=$INTERFACE [ssid]=$SSID [state]=${STATE,,} [icon]=$(icon))
echo ${OUTPUT[$1]}

exit 0
