#!/usr/bin/env bash

OCCUPIED=$(hyprctl workspaces -j | jq -r '.[].id' | tr '\n' ' ')
ACTIVE=$(hyprctl activeworkspace -j | jq -r .id)

case $1 in
    active) echo $ACTIVE
	    ;;
    occupied) echo $OCCUPIED
	      ;;    
esac
