# Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'

# format = """$all"""

format = """$directory$character"""
right_format = "$python$nodejs$rust$golang$git_branch$git_status"

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜ ](bold green)' # The 'success_symbol' segment is being set to '❯' with the color 'bold green'
error_symbol = "[!!](bold red)"
# ~/.config/starship.toml

[username]
style_user = 'yellow italic'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

[directory]
format = '[$path]($style) '
style = 'bold italic cyan'

# ~/.config/starship.toml

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)[$hostname](italic blue)'
#trim_at = '.companyname.com'
disabled = false

# ~/.config/starship.toml

[git_branch]
format = 'git:[$branch]($style) '
style = 'black bold'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
